=begin
#DVC AMS API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 2.0.0_alpha1
Contact: marco.storto@tecniplast.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.0.0

=end

require 'date'

module OpenapiClient
  class LedColor
    
    FALSE = 'false'.freeze
    RED = 'Red'.freeze
    GREEN = 'Green'.freeze
    BLUE = 'Blue'.freeze
    YELLOW = 'Yellow'.freeze
    ALARM = 'Alarm'.freeze
    ANOMALY = 'Anomaly'.freeze
    DIRTY_CAGE = 'DirtyCage'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = LedColor.constants.select { |c| LedColor::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #LedColor" if constantValues.empty?
      value
    end
  end
end
