=begin
#DVC AMS API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 2.0.0
Contact: marco.storto@tecniplast.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.0.0

=end

require 'date'

module Tecniplast
  class WorkUnitStatus
    
    PLANNED = 'Planned'.freeze
    CANT_BE_DONE = 'CantBeDone'.freeze
    COMPLETED = 'Completed'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = WorkUnitStatus.constants.select { |c| WorkUnitStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #WorkUnitStatus" if constantValues.empty?
      value
    end
  end
end
