=begin
#DVC AMS API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 2.0.0_alpha1
Contact: marco.storto@tecniplast.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::HooksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'HooksApi' do
  before do
    # run before each test
    @instance = OpenapiClient::HooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HooksApi' do
    it 'should create an instance of HooksApi' do
      expect(@instance).to be_instance_of(OpenapiClient::HooksApi)
    end
  end

  # unit tests for hooks_post
  # By posting on this endpoint you will register a subscriber to the DVC. One subscriber can receive different kinds of events
  # @param [Hash] opts the optional parameters
  # @option opts [HooksRequest] :hooks_request 
  # @return [HooksResponse]
  describe 'hooks_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
