=begin
#DVC AMS API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 2.0.0
Contact: marco.storto@tecniplast.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Tecniplast::TasksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TasksApi' do
  before do
    # run before each test
    @instance = Tecniplast::TasksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TasksApi' do
    it 'should create an instance of TasksApi' do
      expect(@instance).to be_instance_of(Tecniplast::TasksApi)
    end
  end

  # unit tests for jobs_get
  # get list of tasks planned for today
  # @param [Hash] opts the optional parameters
  # @option opts [WorkUnitType] :work_unit_type Filters by type
  # @option opts [WorkUnitStatus] :work_unit_status Filters by status
  # @option opts [String] :planned_date Filter by planned date, in ISO 8601 format
  # @option opts [Integer] :start page start
  # @option opts [Integer] :size page size
  # @return [WorkUnitsList]
  describe 'jobs_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for jobs_uuid_close_post
  # report task completion
  # @param uuid id of task
  # @param user username of the user performing the change
  # @param [Hash] opts the optional parameters
  # @option opts [Body] :body 
  # @return [nil]
  describe 'jobs_uuid_close_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
