=begin
#DVC AMS API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 2.0.0
Contact: marco.storto@tecniplast.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Tecniplast::CageSplitsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CageSplitsInner' do
  before do
    # run before each test
    @instance = Tecniplast::CageSplitsInner.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CageSplitsInner' do
    it 'should create an instance of CageSplitsInner' do
      expect(@instance).to be_instance_of(Tecniplast::CageSplitsInner)
    end
  end
  describe 'test attribute "ams_cage_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "mice"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
