=begin
#DVC AMS API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 2.0.0_alpha1
Contact: marco.storto@tecniplast.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.0.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/authentication_anonymous'
require 'openapi_client/models/authentication_basic'
require 'openapi_client/models/authentication_token'
require 'openapi_client/models/bedding_change_request'
require 'openapi_client/models/cage_label'
require 'openapi_client/models/cage_movement_event'
require 'openapi_client/models/cage_movement_event_rack'
require 'openapi_client/models/cage_movement_event_reader'
require 'openapi_client/models/cage_movement_events'
require 'openapi_client/models/cage_position'
require 'openapi_client/models/cage_prepared_event'
require 'openapi_client/models/cage_type'
require 'openapi_client/models/cages_list'
require 'openapi_client/models/hook_purpose'
require 'openapi_client/models/hooks_request'
require 'openapi_client/models/hooks_request_endpoints'
require 'openapi_client/models/hooks_response'
require 'openapi_client/models/hooks_response_inner'
require 'openapi_client/models/inline_response404'
require 'openapi_client/models/inline_response4041'
require 'openapi_client/models/led_body'
require 'openapi_client/models/led_color'
require 'openapi_client/models/mouse'
require 'openapi_client/models/new_cage'
require 'openapi_client/models/new_cage_hood'
require 'openapi_client/models/new_cage_rack'
require 'openapi_client/models/user'
require 'openapi_client/models/user_list'
require 'openapi_client/models/work_unit'
require 'openapi_client/models/work_unit_status'
require 'openapi_client/models/work_unit_type'
require 'openapi_client/models/work_units_list'

# APIs
require 'openapi_client/api/bedding_change_api'
require 'openapi_client/api/cages_api'
require 'openapi_client/api/hooks_api'
require 'openapi_client/api/leds_api'
require 'openapi_client/api/tasks_api'
require 'openapi_client/api/users_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
