=begin
#DVC AMS API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 2.0.0_alpha1
Contact: marco.storto@tecniplast.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.0.0

=end

require 'uri'

module OpenapiClient
  class HooksApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # By posting on this endpoint you will register a subscriber to the DVC. One subscriber can receive different kinds of events
    # @param [Hash] opts the optional parameters
    # @option opts [HooksRequest] :hooks_request 
    # @return [HooksResponse]
    def hooks_post(opts = {})
      data, _status_code, _headers = hooks_post_with_http_info(opts)
      data
    end

    # By posting on this endpoint you will register a subscriber to the DVC. One subscriber can receive different kinds of events
    # @param [Hash] opts the optional parameters
    # @option opts [HooksRequest] :hooks_request 
    # @return [Array<(HooksResponse, Fixnum, Hash)>] HooksResponse data, response status code and response headers
    def hooks_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HooksApi.hooks_post ...'
      end
      # resource path
      local_var_path = '/hooks'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'hooks_request'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'HooksResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HooksApi#hooks_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
